/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadc",
        "secondary": "#47607e",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "on-secondary-fixed": "#001d36",
        "surface": "#f7f9fb",
        "on-primary-container": "#79849d",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c4c6cc",
        "background": "#f7f9fb",
        "outline": "#74777d",
        "primary-container": "#101b30",
        "surface-tint": "#545e76",
        "surface-container-high": "#e6e8ea",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#44474c",
        "on-primary-fixed-variant": "#3c475d",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#bbc6e2",
        "surface-container": "#eceef0",
        "primary-fixed": "#d7e2ff",
        "tertiary-fixed": "#6ffbbe",
        "secondary-container": "#c2dcff",
        "secondary-fixed": "#d1e4ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-container": "#48617e",
        "tertiary-container": "#002113",
        "on-primary-fixed": "#101b30",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#bbc6e2",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#009668",
        "on-secondary-fixed-variant": "#2f4865",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#afc9ea",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}

